name: KumaReports
version: ${project.version}
main: com.realxode.kumareports.Main
authors: [ RealXode ]
description: Report players and bugs.

commands:
  report:
    description: Report pleyers, bugs or ask for help
